version: '3.8'

services:
  wanie:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'wanie:latest'
    container_name: wanie
    env_file:
      - .env
    environment:
      HOST: '0.0.0.0'
      FE_PORT: '55111'
      BE_PORT: '55222'
      WANIE_DATA_DIR: /app/storage
      WANIE_HOME: /app/storage
      WANIE_AUTO_OPEN: '${WANIE_AUTO_OPEN}'
      WANIE_USE_WWEBJS: '${WANIE_USE_WWEBJS}'
      WANIE_ALLOW_MOCK: '${WANIE_ALLOW_MOCK}'
      DATABASE_URL: '${DATABASE_URL}'
    volumes:
      - 'wanie-storage:/app/storage'
    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wanie.rule=Host(`wanie.commitflow.space`)"
      - "traefik.http.routers.wanie.entrypoints=websecure"
      - "traefik.http.routers.wanie.tls=true"
      - "traefik.http.services.wanie.loadbalancer.server.port=55111"

    networks:
      - coolify

volumes:
  wanie-storage:

networks:
  coolify:
    external: true
